language: node_js

node_js:
  - 7
  - stable

cache:
  directories:
    - 'node_modules'

before_install:
  - sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
  - rm yarn.lock

install:
  - yarn

script:
  - yarn lint
